import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';

/**
 * Generates a professional 5-page PDF from quotation data.
 * @param {Object} quotationData - The JSON generated by AI.
 * @param {string} style - 'corporate' | 'modern' | 'minimal'
 * @param {Object} dynamicImages - { mobileHome, mobileFlow, dashboard } base64 strings
 * @returns {Promise<Buffer>} The PDF buffer.
 */
export const generateQuotationPDF = async (quotationData, style = 'corporate', dynamicImages = {}) => {
    const browser = await puppeteer.launch({
        headless: "new",
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();

    // Read logo and convert to base64
    let logoBase64 = "";
    try {
        const logoPath = path.resolve('assets/logo.png');
        if (fs.existsSync(logoPath)) {
            logoBase64 = `data:image/png;base64,${fs.readFileSync(logoPath).toString('base64')}`;
        }
    } catch (err) {
        console.error("Error reading logo:", err);
    }

    // ── Theme Variables ──────────────────────────────────────────
    const themes = {
        corporate: {
            primary: '#1a1a2e',
            primaryDark: '#0d0d1a',
            secondary: '#92400e',
            accent: '#fef3c7',
            text: '#1a1a2e',
            muted: '#6b7280',
            bg: '#fafaf9',
            border: '#e5e7eb',
        },
        modern: {
            primary: '#1a1a2e',
            primaryDark: '#0d0d1a',
            secondary: '#d97706',
            accent: '#fef3c7',
            text: '#1a1a2e',
            muted: '#6b7280',
            bg: '#fffdf7',
            border: '#e5e7eb',
        },
        minimal: {
            primary: '#111111',
            primaryDark: '#000000',
            secondary: '#525252',
            accent: '#f5f5f5',
            text: '#111111',
            muted: '#737373',
            bg: '#ffffff',
            border: '#e5e5e5',
        },
    };

    const t = themes[style] || themes.corporate;
    const chunkArray = (arr, size) => {
        const res = [];
        for (let i = 0; i < arr.length; i += size) res.push(arr.slice(i, i + size));
        return res;
    };

    const logoUrl = "https://res.cloudinary.com/dt4vwprm3/image/upload/v1764744525/WhatsApp_Image_2025-12-03_at_12.13.54_PM_rhgci7.jpg";
    const logoHtml = `<img src="${logoUrl}" style="height:50px; object-fit:contain;" />`;

    // ── Per-page section header (slim branding bar) ─────────────
    const headerBlock = () => `
        <div style="display:flex; justify-content:space-between; align-items:center;
                    border-bottom: 3px solid ${t.primary}; padding-bottom:12px; margin-bottom:32px;">
            <div style="display:flex; align-items:center; gap:10px;">
                ${logoHtml}
                <div>
                    <div style="font-size:13px; font-weight:800; color:${t.primary}; letter-spacing:0.5px;">${brandLabel}</div>
                    <div style="font-size:10px; font-weight:600; color:${t.secondary}; text-transform:uppercase; letter-spacing:1px;">Digital Engineering &amp; AI Solutions</div>
                </div>
            </div>
            <div style="text-align:right; font-size:10px; font-weight:600; color:${t.primary}; line-height:1.7;">
                <div>&#128222; +91 86504 20948</div>
                <div>hello@argomsob.onmicrosoft.com</div>
                <div>Date: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
            </div>
        </div>
    `;

    // ── Static Header Label ───────────────────────────────────
    const brandLabel = "ARGOSMOB TECH & AI";

    const sectionNumber = (num, title) => `
        <div style="display:flex; align-items:center; gap:16px; margin-bottom:20px; margin-top:10px;">
            <div style="background:${t.primary}; color:white; font-size:18px; font-weight:900;
                        width:44px; height:44px; border-radius:50%; display:flex;
                        align-items:center; justify-content:center; flex-shrink:0;">
                ${num}
            </div>
            <h1 style="margin:0; font-size:26px; font-weight:800; color:${t.primary}; letter-spacing:-0.5px;">
                ${title}
            </h1>
        </div>
        <hr style="border:none; border-top: 2px solid ${t.accent}; margin-bottom:16px;" />
    `;

    // Renders an array of bullet points or a plain string
    const renderBullets = (data) => {
        if (Array.isArray(data) && data.length > 0) {
            return `<ul style="margin:0 0 8px 0; padding-left:14px; list-style:none;">
                ${data.map(pt => `
                    <li style="display:flex; gap:6px; align-items:flex-start; margin-bottom:3px;">
                        <span style="color:${t.primary}; font-weight:700; font-size:13px; margin-top:1px; flex-shrink:0;">›</span>
                        <span style="font-size:13px; line-height:1.5; color:${t.text}; word-wrap:break-word;">${pt}</span>
                    </li>`
            ).join('')}
            </ul>`;
        }
        // Fallback for missing or empty data
        const fallbackText = typeof data === 'string' && data.length > 0 ? data : "Strategic details being finalized for this specific business module.";
        return `<p style="font-size:13px; line-height:1.5; color:${t.muted}; font-style:italic; margin:0 0 16px 0;">${fallbackText}</p>`;
    };

    const featureCard = (f) => `
        <div style="background:${t.accent}; border-left:4px solid ${t.primary}; border-radius:6px;
                    padding:12px 16px; margin-bottom:12px;
                    page-break-inside:avoid; break-inside:avoid; overflow:hidden;">
            <h3 style="margin:0 0 8px 0; font-size:14px; font-weight:700; color:${t.primary};">
                ${f.module}
            </h3>
            <ul style="margin:0; padding-left:20px; list-style:disc; color:${t.text};">
                ${(f.items || []).map(item => `
                    <li style="font-size:12px; line-height:1.7; margin-bottom:4px; page-break-inside:avoid; break-inside:avoid;">${item}</li>
                `).join('')}
            </ul>
        </div>
    `;

    const timelineItem = (t_data, idx) => {
        let title = '';
        let tasks = [];
        if (typeof t_data === 'object') {
            title = [t_data.phase || t_data.task || `Phase ${idx + 1}`, t_data.duration ? `(${t_data.duration})` : ''].filter(Boolean).join(' ');
            tasks = Array.isArray(t_data.tasks) ? t_data.tasks : [];
        } else {
            title = t_data;
        }
        return `
            <div style="display:flex; gap:14px; margin-bottom:16px; align-items:flex-start;">
                <div style="background:${t.primary}; color:white; font-size:11px; font-weight:700;
                            width:28px; height:28px; border-radius:50%; display:flex;
                            align-items:center; justify-content:center; flex-shrink:0; margin-top:2px;">
                    ${idx + 1}
                </div>
                <div style="flex:1;">
                    <div style="font-size:13px; font-weight:700; color:${t.primary}; margin-bottom:4px;">${title}</div>
                    ${tasks.length > 0 ? `<ul style="margin:0; padding-left:16px; list-style:disc;">
                        ${tasks.map(task => `<li style="font-size:12px; color:${t.text}; line-height:1.6; margin-bottom:2px;">${task}</li>`).join('')}
                    </ul>` : ''}
                </div>
            </div>
        `;
    };

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root {
            --primary: ${t.primary};
            --primary-dark: ${t.primaryDark};
            --secondary: ${t.secondary};
            --accent: ${t.accent};
            --text: ${t.text};
            --muted: ${t.muted};
            --bg: ${t.bg};
            --border: ${t.border};
        }
        * { box-sizing: border-box; -webkit-print-color-adjust: exact; }
        body {
            font-family: 'Inter', sans-serif;
            margin: 0; padding: 0;
            color: var(--text);
            background: white;
            line-height: 1.5;
        }
        .page {
            width: 210mm;
            height: 297mm;
            padding: 20mm 15mm 25mm 15mm;
            position: relative;
            box-sizing: border-box;
            background: var(--bg);
            overflow: hidden;
        }
        .page::after {
            content: "ArgosMob Tech & AI PVT Ltd.";
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 80px;
            color: rgba(0, 0, 0, 0.03);
            white-space: nowrap;
            pointer-events: none;
            z-index: -1;
            font-weight: 900;
            text-transform: uppercase;
        }
        .page-break { page-break-before: always; break-before: page; }

        /* Typography */
        h1, h2, h3, h4 { margin: 0; font-weight: 800; color: var(--primary); }
        p { margin: 0 0 10px 0; font-size: 11px; color: var(--text); }
        li { font-size: 11px; margin-bottom: 4px; }

        /* ── Cover Page ── */
        .cover {
            width: 210mm;
            height: 297mm;
            background: linear-gradient(135deg, #e0f2ff 0%, #ffffff 100%);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 24mm 18mm;
            color: var(--primary);
            box-sizing: border-box;
            position: relative;
        }
        .cover h1, .cover div { color: var(--primary) !important; }

        /* ── TOC ── */
        .toc-list { margin-top: 20px; }
        .toc-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 14px 0;
            border-bottom: 1px solid var(--border);
        }
        .toc-label { display: flex; align-items: center; gap: 15px; font-weight: 700; font-size: 15px; }
        .toc-index { 
            background: var(--accent); color: var(--primary); 
            padding: 2px 8px; border-radius: 6px; font-size: 12px;
        }

        /* ── Branding ── */
        .header-bar {
            display: flex; justify-content: space-between; align-items: center;
            border-bottom: 2px solid var(--primary); padding-bottom: 12px; margin-bottom: 20px;
        }
        .section-tag {
            background: var(--primary); color: white;
            padding: 4px 12px; border-radius: 4px;
            font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px;
            display: inline-block; margin-bottom: 10px;
        }

        /* ── Components ── */
        .glass-box {
            background: #ffffff;
            border: 1px solid #d1d5db;
            border-radius: 12px;
            padding: 18px;
            margin-bottom: 20px;
            min-height: 80px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.02);
        }
        .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        
        /* ── Feature Cards ── */
        .feature-card {
            background: white; border: 1px solid var(--border);
            border-radius: 10px; padding: 15px; margin-bottom: 15px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
            break-inside: avoid;
        }
        .feature-title { font-size: 14px; margin-bottom: 10px; border-left: 3px solid var(--primary); padding-left: 10px; }

        /* ── Visual Frames ── */
        .hero-vision {
            width: 100%; height: 300px; border-radius: 10px; overflow: hidden;
            box-shadow: 0 15px 30px rgba(0,0,0,0.08); margin: 15px 0; border: 1px solid var(--border);
        }
        .hero-vision img { width: 100%; height: 100%; object-fit: cover; }

        .device-container {
            display: flex; justify-content: center; gap: 30px; align-items: flex-end; padding: 20px 0;
        }
        .mobile-mockup {
            width: 200px; height: 410px; background: #000; border-radius: 32px;
            padding: 10px; position: relative; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
        }
        .mobile-screen {
            width: 100%; height: 100%; background: #eee; border-radius: 24px;
            overflow: hidden; display: flex; align-items: center; justify-content: center;
        }
        .mobile-screen img { width: 100%; height: 100%; object-fit: contain; }

        .web-mockup {
            width: 100%; background: #fff; border-radius: 12px; border: 1px solid var(--border);
            overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.2);
        }
        .web-header { background: #f3f4f6; padding: 8px 15px; border-bottom: 1px solid var(--border); display: flex; gap: 5px; }
        .web-screen { width: 100%; min-height: 250px; background: #fff; }
        .web-screen img { width: 100%; height: auto; display: block; object-fit: contain; }

        /* ── Footer ── */
        .footer {
            position: absolute; bottom: 0; left: 0; right: 0;
            height: 18mm; padding: 0 18mm 8mm 18mm;
            background: #ffffff; z-index: 9999;
            border-top: 1px solid var(--border);
            display: flex; justify-content: space-between; align-items: center;
            font-size: 10px; font-weight: 600; color: var(--muted);
        }

        /* ── Mermaid Styling ── */
        .mermaid { display: flex; justify-content: center; align-items: center; width: 100%; height: 100%; }
        .mermaid svg { 
            max-width: 100% !important; 
            max-height: 100% !important; 
            height: auto !important;
            width: auto !important;
        }
    </style>
</head>
<body>

<!-- PAGE 1: COVER -->
<div class="cover">
    <div style="display:flex; align-items:center; gap:12px;">
        <img src="${logoUrl}" style="height:60px; object-fit:contain;" />
        <div>
            <div style="font-weight:900; font-size:18px; color:var(--primary);">ARGOSMOB TECH &amp; AI</div>
            <div style="font-size:10px; text-transform:uppercase; letter-spacing:2px; color:var(--muted);">Bespoke Digital Engineering</div>
        </div>
    </div>
    <div style="text-align:center;">
        <div style="text-transform:uppercase; letter-spacing:6px; font-size:11px; margin-bottom:20px; opacity:0.7;">Solution Proposal</div>
        <h1 style="color:white; font-size:56px; line-height:1; margin-bottom:15px; letter-spacing:-2px;">${quotationData.projectName}</h1>
        <div style="font-size:20px; font-weight:600; opacity:0.9;">Prepared for: ${quotationData.clientName}</div>
        <div style="margin-top:40px; display:inline-block; border:1px solid rgba(255,255,255,0.3); padding:8px 24px; border-radius:30px; font-size:12px;">2026 STRATEGIC EDITION</div>
    </div>
    <div style="display:flex; justify-content:space-between; font-size:11px; color:var(--muted); border-top:1px solid rgba(0,0,0,0.1); padding-top:20px;">
        <div>✉ hello@argomsob.onmicrosoft.com</div>
        <div>📍 Greater Noida, UP, India</div>
        <div>&#128197; ${new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</div>
    </div>
</div>

<!-- PAGE 2: TOC -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">DOCUMENT STRUCTURE</div>
        <div style="font-size:10px; color:var(--muted);">${quotationData.projectName} Proposal</div>
    </div>
    <h1 style="font-size:36px; margin-bottom:10px;">Table of Contents</h1>
    <div class="toc-list">
        <div class="toc-item"><div class="toc-label"><span class="toc-index">01</span> Executive Vision</div><span>03</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">02</span> Strategic Framework</div><span>04</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">03</span> Technical Scope</div><span>05</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">04</span> Project Boundaries</div><span>06</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">05</span> Architectural Diagrams</div><span>07</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">06</span> User Flow & Journey</div><span>08</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">07</span> Functional Architecture</div><span>09</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">08</span> Implementation Roadmap</div><span>10</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">09</span> Commercial Strategy</div><span>11</span></div>
        <div class="toc-item"><div class="toc-label"><span class="toc-index">10</span> Legal Disclosure</div><span>12</span></div>
    </div>
    <div class="footer"><span>ArgosMob Confidential</span><span>Page 02</span></div>
</div>

<!-- PAGE 3: VISION & PROBLEM -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">01 EXECUTIVE VISION</div>
        <div style="font-size:10px; color:var(--muted);">Proposal for ${quotationData.clientName}</div>
    </div>
    
    <div class="section-tag">Target Objectives</div>
    <h1 style="font-size:28px; margin-bottom:20px;">Project Overview</h1>
    
    <div class="glass-box">
        <h4 style="font-size:12px; text-transform:uppercase; letter-spacing:1px; color:var(--secondary); margin-bottom:10px;">The Challenge</h4>
        <p style="font-size:14px; font-weight:500;">${quotationData.problemStatement || 'Addressing core operational inefficiencies with modern technology.'}</p>
    </div>

    <div style="margin-bottom: 15px;">
        <h4 style="font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: var(--secondary); margin-bottom: 10px;">Solution Objectives</h4>
        ${renderBullets(quotationData.overview)}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 03</span></div>
</div>

<!-- PAGE 4: STRATEGIC FRAMEWORK (METHODOLOGY & SECURITY) -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">02 STRATEGIC FRAMEWORK</div>
        <div style="font-size:10px; color:var(--muted);">Security &amp; Methodology</div>
    </div>

    <div class="grid-2">
        <div>
            <div class="section-tag">Agile Process</div>
            <h2 style="font-size:22px; margin-bottom:15px;">Development Methodology</h2>
            <div class="glass-box" style="padding:15px; margin-bottom:10px;">
                ${renderBullets(quotationData.methodology)}
            </div>
        </div>
        <div>
            <div class="section-tag">Data Sovereignty</div>
            <h2 style="font-size:22px; margin-bottom:15px;">Enterprise Security</h2>
            <div class="glass-box" style="padding:15px; border-left:4px solid var(--primary); margin-bottom:10px;">
                ${renderBullets(quotationData.security)}
            </div>
        </div>
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 04</span></div>
</div>

<!-- PAGE 5: STRATEGIC FRAMEWORK (TECHNICAL SCOPE) -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">02 STRATEGIC FRAMEWORK</div>
        <div style="font-size:10px; color:var(--muted);">Detailed Technical Scope</div>
    </div>

    <div class="section-tag">Implementation Boundaries</div>
    <h1 style="font-size:28px; margin-bottom:20px;">Technical Scope</h1>
    
    <div class="glass-box" style="padding:25px; margin-bottom:20px;">
        ${renderBullets(quotationData.scope)}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 05</span></div>
</div>

<!-- PAGE 6: STRATEGIC FRAMEWORK (ASSUMPTIONS & CONSTRAINTS) -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">02 STRATEGIC FRAMEWORK</div>
        <div style="font-size:10px; color:var(--muted);">Implementation Boundaries</div>
    </div>

    <div class="grid-2" style="margin-top:20px;">
        <div>
            <div class="section-tag">Strategic Premises</div>
            <h3 style="font-size:16px; margin-bottom:12px;">Project Assumptions</h3>
            <div class="glass-box" style="padding:15px; border-top:3px solid var(--primary);">
                ${renderBullets(quotationData.assumptions)}
            </div>
        </div>
        <div>
            <div class="section-tag">Operational Limits</div>
            <h3 style="font-size:16px; margin-bottom:12px;">Technical Constraints</h3>
            <div class="glass-box" style="padding:15px; border-top:3px solid var(--secondary);">
                ${renderBullets(quotationData.constraints)}
            </div>
        </div>
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 06</span></div>
</div>

<!-- PAGE 6: TECH BLUEPRINT (DIAGRAMS) -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">03 TECHNICAL BLUEPRINT</div>
        <div style="font-size:10px; color:var(--muted);">System Architecture</div>
    </div>

    <div class="section-tag">Visualizing the flow</div>
    <h1 style="font-size:26px; margin-bottom:15px;">Architectural Diagrams</h1>

    <div style="display:grid; grid-template-columns: 1fr 1fr; gap:20px;">
        ${(quotationData.visuals?.diagrams || []).map(d => `
            <div class="glass-box" style="margin-bottom:0; padding:20px; height:420px; display:flex; flex-direction:column;">
                <h4 style="font-size:12px; margin:0 0 12px 0; color:var(--primary); text-align:center; font-weight:800; text-transform:uppercase; letter-spacing:1px;">${d.title}</h4>
                <div style="flex:1; display:flex; align-items:center; justify-content:center; overflow:hidden;">
                    <div class="mermaid">${(d.mermaid || '').replace(/`/g, '').replace(/\\/g, '')}</div>
                </div>
            </div>
        `).join('')}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 07</span></div>
</div>

<!-- PAGE 7: USER FLOW & JOURNEY -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">05 USER FLOW & JOURNEY</div>
        <div style="font-size:10px; color:var(--muted);">User Experience & Interaction</div>
    </div>

    <div class="section-tag">User-Centric Design</div>
    <h1 style="font-size:26px; margin-bottom:15px;">User Flow & Journey</h1>

    <div style="display:grid; grid-template-columns: 1fr 1fr; gap:20px;">
        ${(quotationData.visuals?.userFlows || []).map(d => `
            <div class="glass-box" style="margin-bottom:0; padding:20px; height:420px; display:flex; flex-direction:column;">
                <h4 style="font-size:12px; margin:0 0 12px 0; color:var(--primary); text-align:center; font-weight:800; text-transform:uppercase; letter-spacing:1px;">${d.title}</h4>
                <div style="flex:1; display:flex; align-items:center; justify-content:center; overflow:hidden;">
                    <div class="mermaid">${(d.mermaid || '').replace(/`/g, '').replace(/\\/g, '')}</div>
                </div>
            </div>
        `).join('')}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 08</span></div>
</div>

<!-- PAGE 8: FUNCTIONAL ARCHITECTURE (FEATURES) -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">06 FUNCTIONAL ARCHITECTURE</div>
        <div style="font-size:10px; color:var(--muted);">Core Feature Breakdown</div>
    </div>

    <div style="column-count: 2; column-gap: 16px;">
        ${(quotationData.features || []).length > 0 ? (quotationData.features).map(f => `
            <div class="feature-card" style="break-inside: avoid; page-break-inside: avoid; margin-bottom:12px;">
                <h4 class="feature-title" style="margin-bottom:4px;">${f.module || 'System Module'}</h4>
                <p style="font-size:10px; color:var(--muted); margin:0 0 8px 0; line-height:1.4;">${f.description || 'Enterprise-grade implementation of core business logic and workflow orchestration.'}</p>
                <ul style="margin:0; padding-left:15px; font-size:11px; color:var(--text); line-height:1.5;">
                    ${(f.items || []).map(item => `<li>${item}</li>`).join('')}
                </ul>
            </div>
        `).join('') : `
            <div class="glass-box" style="column-span: all; text-align:center; padding:40px;">
                <p style="color:var(--muted); font-style:italic;">Feature architecture is being mapped to specific user stories.</p>
            </div>
        `}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 09</span></div>
</div>

<!-- PAGE 9: IMPLEMENTATION ROADMAP -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">07 IMPLEMENTATION ROADMAP</div>
        <div style="font-size:10px; color:var(--muted);">Tech Stack &amp; Delivery</div>
    </div>

        <div style="grid-column: span 2;">
            <div class="section-tag">Foundations</div>
            <h3 style="font-size:18px; margin-bottom:15px;">Graphical Technology Stack</h3>
            <div style="display:grid; grid-template-columns: repeat(4, 1fr); gap:12px;">
                ${(quotationData.techStack || []).map(s => {
        const lowTech = s.toLowerCase();
        let iconColor = 'var(--primary)';
        let iconPath = '<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>';

        if (lowTech.includes('react')) {
            iconColor = '#61dafb';
            iconPath = '<circle cx="12" cy="12" r="2"/><path d="M12 12c-4 0-8 3.5-8 3.5s4 3.5 8 3.5 8-3.5 8-3.5-4-3.5-8-3.5z" transform="rotate(30 12 12)"/><path d="M12 12c-4 0-8 3.5-8 3.5s4 3.5 8 3.5 8-3.5 8-3.5-4-3.5-8-3.5z" transform="rotate(150 12 12)"/><path d="M12 12c-4 0-8 3.5-8 3.5s4 3.5 8 3.5 8-3.5 8-3.5-4-3.5-8-3.5z" transform="rotate(270 12 12)"/>';
        }
        else if (lowTech.includes('node')) {
            iconColor = '#339933';
            iconPath = '<path d="m12 3-8 4.5v9l8 4.5 8-4.5v-9L12 3Z"/><path d="m12 12 8-4.5"/><path d="M12 21v-9"/><path d="m4 7.5 8 4.5"/>';
        }
        else if (lowTech.includes('supabase')) {
            iconColor = '#3ecf8e';
            iconPath = '<path d="m12 3-10 9h4v9l10-9h-4v-9Z"/>';
        }
        else if (lowTech.includes('razorpay') || lowTech.includes('payment')) {
            iconColor = '#3395ff';
            iconPath = '<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/>';
        }
        else if (lowTech.includes('aws') || lowTech.includes('cloud')) {
            iconColor = '#FF9900';
            iconPath = '<path d="M17.5 19c2.5 0 4.5-2 4.5-4.5 0-2-1.5-3.5-3.5-4-.5-4-4.5-6.5-8.5-4.5-2-3-7-1.5-7.5 3-2 .5-3.5 2.5-3.5 4.5 0 2.5 2 4.5 4.5 4.5h14z"/>';
        }
        else if (lowTech.includes('docker')) {
            iconColor = '#2496ED';
            iconPath = '<path d="M22 12.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V12a.5.5 0 0 1 .5-.5h5V5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v2.5h2V6a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v1.5h2V9a.5.5 0 0 1 .5-.5H22a.5.5 0 0 1 .5.5v3.5z"/><path d="M2 12a10 10 0 0 0 20 0"/>';
        }
        else if (lowTech.includes('mobile') || lowTech.includes('native')) {
            iconColor = '#4E4E4E';
            iconPath = '<rect x="5" y="2" width="14" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12.01" y2="18"/>';
        }

        return `
                        <div style="background:var(--bg); border:1px solid var(--border); border-radius:12px; padding:15px 10px; text-align:center; box-shadow:0 4px 6px -1px rgba(0,0,0,0.05); min-height:100px; display:flex; flex-direction:column; align-items:center; justify-content:center;">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="${iconColor}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-bottom:10px;">
                                ${iconPath}
                            </svg>
                            <div style="font-size:10px; font-weight:800; color:var(--text); line-height:1.2; text-transform:uppercase; letter-spacing:0.5px;">${s}</div>
                        </div>`;
    }).join('')}
            </div>
        </div>

    <div class="section-tag">Execution Plan</div>
    <h3 style="font-size:18px; margin-bottom:15px;">Project Timeline</h3>
    <div style="position:relative; padding-left:20px; border-left:2px solid var(--border); margin-bottom:20px;">
        ${(quotationData.timeline || []).length > 0 ? (quotationData.timeline).map((t, i) => `
            <div style="margin-bottom:12px; position:relative; break-inside:avoid;">
                <div style="position:absolute; left:-29px; top:0; width:16px; height:16px; border-radius:50%; background:var(--primary); border:4px solid var(--bg);"></div>
                <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                    <div style="font-size:13px; font-weight:800;">${t.phase || `Phase ${i + 1}`}</div>
                    <div style="font-size:10px; font-weight:800; color:var(--secondary); background:var(--accent); padding:2px 10px; border-radius:4px;">${t.duration || 'TBD'}</div>
                </div>
                <div style="font-size:10px; color:var(--muted); margin-top:2px;">${(t.tasks || []).join(' • ') || 'Implementation tasks being scheduled.'}</div>
            </div>
        `).join('') : `
            <p style="color:var(--muted); font-style:italic; padding:20px 0;">Delivery roadmap is being finalized based on technical dependencies.</p>
        `}
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 10</span></div>
</div>

<!-- PAGE 10: COMMERCIAL STRATEGY -->
<div class="page page-break" style="background: white;">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">08 COMMERCIAL STRATEGY</div>
        <div style="font-size:10px; color:var(--muted);">Financial Model</div>
    </div>

    <div class="grid-2" style="margin-bottom:20px;">
        ${(quotationData.visuals?.analytics || []).map((chart, idx) => `
            <div style="background:var(--bg); border-radius:12px; padding:15px; text-align:center;">
                <h4 style="font-size:12px; margin-bottom:10px;">${chart.title}</h4>
                <canvas id="chart-${idx}" style="max-height:140px;"></canvas>
            </div>
        `).join('')}
    </div>

    <div style="background:linear-gradient(135deg, var(--primary), var(--primary-dark)); border-radius:18px; padding:30px; color:white; text-align:center;">
        <div style="text-transform:uppercase; letter-spacing:4px; font-size:12px; opacity:0.75; margin-bottom:10px;">Consultancy &amp; Execution Investment</div>
        <h1 style="color:white; font-size:42px; letter-spacing:-2px; margin-bottom:8px;">${quotationData.commercialEstimate}</h1>
        <div style="font-size:11px; opacity:0.6;">Exclusive of prevailing GST (18%) and specialized 3rd party API subscriptions</div>
    </div>

    <div style="margin-top:20px;">
        <h4 style="font-size:13px; margin-bottom:12px;">Strategic Payment Plan & Milestones</h4>
        <div style="display:grid; grid-template-columns: 1fr; gap:8px;">
            ${(quotationData.paymentPlan || []).map((p, i) => `
                <div style="background:var(--bg); border:1px solid var(--border); padding:10px 15px; border-radius:10px; display:flex; gap:12px; align-items:center;">
                    <span style="background:var(--primary); color:white; font-weight:900; width:24px; height:24px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:12px; flex-shrink:0;">${i + 1}</span>
                    <span style="font-size:11px; font-weight:700; color:var(--text);">${p}</span>
                </div>
            `).join('')}
        </div>
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 11</span></div>
</div>

<!-- PAGE 11: LEGAL SIGNOFF -->
<div class="page page-break">
    <div class="header-bar">
        <div style="font-weight:800; font-size:14px; color:var(--primary);">LEGEND &amp; SIGNOFF</div>
        <div style="font-size:10px; color:var(--muted);">Legal Disclosure</div>
    </div>

    <div class="section-tag">Terms of Engagement</div>
    <h1 style="font-size:28px; margin-bottom:20px;">Legal Disclosure</h1>

    <div class="glass-box" style="padding:30px; line-height:1.8; font-size:14px; color:var(--text); border-left:5px solid var(--primary);">
        <p style="font-size:14px; margin-bottom:20px; font-weight:500;">
            This proposal is confidential and intended solely for the named recipient. All intellectual property developed under this engagement remains the property of the client upon full payment. ArgosMob Tech &amp; AI Pvt. Ltd. adheres to applicable Indian IT laws and data protection regulations.
        </p>
        <p style="font-size:14px; margin-top:40px; border-top:1px solid var(--border); padding-top:20px;">
            <strong>Agreed and Accepted:</strong>
        </p>
        <div style="display:grid; grid-template-columns: 1fr 1fr; gap:40px; margin-top:60px;">
            <div>
                <div style="border-bottom:1px solid var(--text); height:40px;"></div>
                <div style="font-size:11px; margin-top:8px; font-weight:700;">For ArgosMob Tech &amp; AI Pvt. Ltd.</div>
            </div>
            <div>
                <div style="border-bottom:1px solid var(--text); height:40px;"></div>
                <div style="font-size:11px; margin-top:8px; font-weight:700;">For ${quotationData.clientName}</div>
            </div>
        </div>
    </div>

    <div class="footer"><span>ArgosMob Confidential</span><span>Page 12</span></div>
</div>

<script>
    // Initialize Mermaid
    mermaid.initialize({ 
        startOnLoad: true, 
        theme: 'base',
        securityLevel: 'loose',
        flowchart: { useMaxWidth: true, htmlLabels: true, curve: 'basis' },
        themeVariables: { 
            primaryColor: '${t.accent}', 
            lineColor: '${t.secondary}',
            primaryBorderColor: '${t.primary}',
            primaryTextColor: '${t.primary}',
            fontSize: '11px',
            fontFamily: 'Inter'
        } 
    });

    // Initialize Charts
    const charData = ${JSON.stringify(quotationData.visuals?.analytics || [])};
    const brandColors = ['${t.primary}', '${t.secondary}', '#4f46e5', '#10b981', '#f59e0b'];
    
    charData.forEach((chart, idx) => {
        const labels = chart.data?.labels || [];
        const values = (chart.data?.values || []).map(v => Number(String(v).replace(/[^0-9.]/g, '')));
        
        const canvas = document.getElementById('chart-' + idx);
        if (!canvas) return;
        
        const ctx = canvas.getContext('2d');
        new Chart(ctx, {
            type: chart.type || 'pie',
            data: {
                labels: labels,
                datasets: [{
                    label: chart.title,
                    data: values,
                    backgroundColor: brandColors,
                    borderWidth: 0
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { 
                        display: chart.type === 'pie',
                        position: 'bottom', 
                        labels: { boxWidth: 8, font: { size: 9, weight: '600' } } 
                    }
                }
            }
        });
    });
</script>

</body>
</html>`;

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    try {
        await page.waitForSelector('.mermaid svg', { timeout: 10000 });
    } catch (e) {
        console.warn("Mermaid rendering timed out or no diagrams present.");
    }

    const pdfBuffer = await page.pdf({
        format: 'A4',
        margin: { top: '0', right: '0', bottom: '0', left: '0' },
        printBackground: true,
        displayHeaderFooter: false,
    });

    await browser.close();
    return pdfBuffer;
};
