import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';

/**
 * Generates a professional PDF for Template 4 (Cost Breakdown Style).
 * Based on Template 3 structure with an added detailed cost breakdown table.
 * @param {Object} quotationData - The JSON generated by AI for Template 4.
 * @param {string} style - Template style identifier.
 * @param {Object} options - Additional options (e.g. includeGST).
 * @returns {Promise<Buffer>} The PDF buffer.
 */
export const generateQuotationPDFTemplate4 = async (quotationData, style, options = {}) => {
    const browser = await puppeteer.launch({
        headless: "new",
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();

    // Corporate Palette
    const t = {
        primary: '#1E3A8A',
        secondary: '#334155',
        accent: '#06B6D4',
        bg: '#F8FAFC',
        text: '#1E293B',
        border: '#E2E8F0',
        white: '#FFFFFF'
    };

    const logoUrl = "https://res.cloudinary.com/dt4vwprm3/image/upload/v1764744525/WhatsApp_Image_2025-12-03_at_12.13.54_PM_rhgci7.jpg";

    const headerBlock = (title) => `
        <div style="display:flex; justify-content:space-between; align-items:flex-end; border-bottom: 2px solid ${t.primary}; padding-bottom: 15px; margin-bottom: 30px;">
            <div>
                <h2 style="font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 20px; color: ${t.primary}; margin: 0; text-transform: uppercase; letter-spacing: 1px;">
                    ${title}
                </h2>
            </div>
            <div style="text-align:right;">
                <img src="${logoUrl}" style="height:35px; object-fit:contain;" />
            </div>
        </div>
    `;

    // Build cost breakdown rows
    const costBreakdownRows = (quotationData.costBreakdown || []).map((row, idx) => `
        <tr>
            <td style="font-weight:500;">${idx + 1}</td>
            <td style="font-weight:600; color:${t.primary};">${row.category}</td>
            <td style="font-size:12px; color:${t.secondary};">${row.description}</td>
            <td style="text-align:right; font-weight:500;">${row.hoursEstimated}</td>
            <td style="text-align:right;">${row.ratePerHour}</td>
            <td style="text-align:right; font-weight:600;">${row.cost}</td>
        </tr>
    `).join('');

    // GST section
    const includeGST = options.includeGST || quotationData.costEstimation?.gstAmount;
    const gstRow = includeGST ? `
        <tr style="background:transparent;">
            <td colspan="5" style="text-align:right; font-weight:600; padding:10px 15px; border:none;">Subtotal</td>
            <td style="text-align:right; font-weight:700; padding:10px 15px; border-bottom:1px solid ${t.border};">${quotationData.costEstimation?.totalCost || 'TBD'}</td>
        </tr>
        <tr style="background:transparent;">
            <td colspan="5" style="text-align:right; font-weight:600; padding:10px 15px; border:none;">GST @ 18%</td>
            <td style="text-align:right; font-weight:600; padding:10px 15px; border-bottom:1px solid ${t.border}; color:${t.secondary};">${quotationData.costEstimation?.gstAmount || 'TBD'}</td>
        </tr>
        <tr style="background:${t.primary};">
            <td colspan="5" style="text-align:right; font-weight:700; padding:12px 15px; border:none; color:${t.white}; font-size:14px;">Grand Total (Incl. GST)</td>
            <td style="text-align:right; font-weight:800; padding:12px 15px; border:none; color:${t.white}; font-size:16px;">${quotationData.costEstimation?.grandTotal || 'TBD'}</td>
        </tr>
    ` : `
        <tr style="background:${t.primary};">
            <td colspan="5" style="text-align:right; font-weight:700; padding:12px 15px; border:none; color:${t.white}; font-size:14px;">Total Cost</td>
            <td style="text-align:right; font-weight:800; padding:12px 15px; border:none; color:${t.white}; font-size:16px;">${quotationData.costEstimation?.totalCost || 'TBD'}</td>
        </tr>
        <tr style="background:transparent;">
            <td colspan="6" style="text-align:right; font-size:11px; color:${t.secondary}; padding:8px 15px; border:none; font-style:italic;">*Exclusive of GST @ 18%</td>
        </tr>
    `;

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Montserrat:wght@600;700;800&display=swap" rel="stylesheet">
    <style>
        @page {
            size: A4;
            margin: 20mm 20mm 25mm 20mm;
        }
        @page :first {
            margin: 0;
        }
        * { box-sizing: border-box; -webkit-print-color-adjust: exact; }
        body {
            font-family: 'Inter', sans-serif;
            margin: 0; padding: 0;
            color: ${t.text};
            background: ${t.white};
            line-height: 1.6;
        }
        .page-break {
            page-break-before: always;
            padding-top: 10px;
        }
        h1, h2, h3, h4 { font-family: 'Montserrat', sans-serif; color: ${t.primary}; margin-top: 0; }
        
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 65px;
            color: rgba(30, 58, 138, 0.04);
            font-family: 'Montserrat', sans-serif;
            font-weight: 800;
            z-index: 1;
            white-space: nowrap;
            pointer-events: none;
        }

        .global-footer {
            border-top: 1px solid ${t.border};
            padding-top: 5px;
            margin-top: 5mm;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            font-size: 9px;
            color: ${t.secondary};
            font-weight: 500;
        }

        .layout-table { width: 100%; border: none; border-collapse: collapse; }
        .layout-table td { padding: 0; border: none; }
        .spacer-header { height: 1px; }

        .cover-container {
            display: flex;
            width: 210mm;
            height: 297mm;
            background: ${t.white};
            position: relative;
            z-index: 50;
            margin-top: -1px;
        }
        .cover-left {
            flex: 1.2;
            padding: 40px 30px 40px 20mm;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .cover-right {
            flex: 0.8;
            background: linear-gradient(135deg, ${t.primary} 0%, ${t.accent} 100%);
            border-top-left-radius: 60px;
            border-bottom-left-radius: 60px;
            position: relative;
            overflow: hidden;
        }
        .cover-right::after {
            content: "";
            position: absolute;
            top: -10%; left: -20%;
            width: 150%; height: 150%;
            background: repeating-linear-gradient(45deg, rgba(255,255,255,0.05) 0px, rgba(255,255,255,0.05) 20px, transparent 20px, transparent 40px);
        }

        table {
            width: 100%; border-collapse: collapse; margin-bottom: 25px;
            font-size: 13px;
        }
        th, td {
            padding: 12px 15px; text-align: left; border-bottom: 1px solid ${t.border};
            page-break-inside: avoid;
        }
        th {
            background-color: ${t.bg}; color: ${t.primary}; font-weight: 600; font-family: 'Montserrat', sans-serif;
        }
        tr:nth-child(even) { background-color: #F8FAFC55; }
        tr { page-break-inside: avoid; }

        .badge {
            display: inline-block; padding: 6px 12px; margin: 0 6px 8px 0;
            background: ${t.bg}; border: 1px solid ${t.border}; border-radius: 4px;
            font-size: 12px; font-weight: 500; color: ${t.secondary};
        }

        .module-box {
            border-left: 3px solid ${t.accent};
            padding: 15px 20px;
            margin-bottom: 20px;
            background: ${t.white};
            border-top: 1px solid ${t.border};
            border-right: 1px solid ${t.border};
            border-bottom: 1px solid ${t.border};
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02);
            page-break-inside: avoid;
        }

        .highlight-box {
            background: rgba(30, 58, 138, 0.04);
            border-left: 4px solid ${t.primary};
            padding: 15px 20px;
            border-radius: 0 6px 6px 0;
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        
        ul { padding-left: 20px; margin-top: 5px; }
        li { margin-bottom: 6px; font-size: 13px; page-break-inside: avoid; }

        .cost-breakdown-table th {
            background: ${t.primary};
            color: ${t.white};
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .cost-breakdown-table td {
            font-size: 12px;
            padding: 10px 15px;
        }
    </style>
</head>
<body>
<div class="watermark">Argosmob Tech and AI Pvt LTD</div>

<!-- 1. Cover Page -->
<div>
    <div class="cover-container">
        <div class="cover-left">
            <img src="${logoUrl}" style="height:60px; object-fit:contain; margin-bottom: 80px;" />
            <div style="text-transform:uppercase; letter-spacing:3px; color:${t.secondary}; font-size:12px; margin-bottom:15px; font-weight:600;">Project Proposal & Cost Breakdown</div>
            <h1 style="font-size:42px; line-height:1.2; margin-bottom:20px;">${quotationData.projectName || 'Software Solution Proposal'}</h1>
            <div style="width: 60px; height: 5px; background: ${t.accent}; margin-bottom: 40px;"></div>
            
            <table style="width:100%; border:none; margin-bottom:0;">
                <tr style="background:transparent;">
                    <td style="padding:5px 0; border:none; color:${t.secondary}; font-size:12px; font-weight:600; width:50%;">PREPARED FOR</td>
                    <td style="padding:5px 0; border:none; color:${t.secondary}; font-size:12px; font-weight:600; width:50%;">PREPARED BY</td>
                </tr>
                <tr style="background:transparent;">
                    <td style="padding:0 0 20px 0; border:none; font-size:16px; font-weight:700; color:${t.primary};">${quotationData.clientName || 'Valued Client'}</td>
                    <td style="padding:0 0 20px 0; border:none; font-size:15px; font-weight:600; color:${t.text};">Argosmob Tech & AI Pvt. Ltd.</td>
                </tr>
                <tr style="background:transparent;">
                    <td colspan="2" style="padding:5px 0; border:none; color:${t.secondary}; font-size:12px; font-weight:600;">DATE</td>
                </tr>
                <tr style="background:transparent;">
                    <td colspan="2" style="padding:0 0 20px 0; border:none; font-size:14px; font-weight:500;">${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</td>
                </tr>
            </table>
        </div>
        <div class="cover-right"></div>
    </div>
</div>

<table class="layout-table" style="page-break-before: always;">
  <thead><tr><td><div class="spacer-header"></div></td></tr></thead>
  <tfoot>
    <tr>
      <td>
        <div class="global-footer">
            <div style="display:flex; flex-direction:column; gap:4px;">
                <span>Email: hello@argosmob.onmicrosoft.com</span>
                <span>Address: 618, Hope Tower, Galaxy Blue Sapphire, Gr. Noida West, 201016</span>
            </div>
            <div style="text-align:right; display:flex; flex-direction:column; justify-content:flex-end;">
                <span>Corporate Proposal</span>
            </div>
        </div>
      </td>
    </tr>
  </tfoot>
  <tbody><tr><td>

    <!-- 2. Introduction & Delivery Scope -->
    <div>
        ${headerBlock('1. Executive Overview')}
        
        <div class="highlight-box">
            <h3 style="font-size:16px; margin-bottom:10px;">Project Introduction</h3>
            <p style="font-size:14px; margin:0;">${quotationData.introduction || ''}</p>
        </div>

        <h3 style="font-size:18px; margin-top:40px; margin-bottom:15px; border-bottom:1px solid ${t.border}; padding-bottom:10px;">2. Delivery Scope</h3>
        <p style="font-size:13px; color:${t.secondary};">The following core components are included in the delivery:</p>
        <div style="display:grid; grid-template-columns: 1fr 1fr; gap:15px; margin-top:20px;">
            ${(quotationData.deliveryScope || []).map(item => `
                <div style="display:flex; align-items:center; gap:10px; page-break-inside: avoid;">
                    <div style="width:8px; height:8px; background:${t.accent}; border-radius:50%;"></div>
                    <span style="font-size:14px; font-weight:500;">${item}</span>
                </div>
            `).join('')}
        </div>
    </div>

    <!-- 3. Key Modules -->
    <div class="page-break">
        ${headerBlock('3. Functional Modules')}
        <p style="font-size:13px; margin-bottom:25px;">The solution architecture is broken down into the following key functional modules.</p>
        
        ${(quotationData.keyModules || quotationData.features || []).map((mod, idx) => `
            <div class="module-box">
                <h4 style="font-size:15px; margin-bottom:8px; display:flex; align-items:center; gap:10px;">
                    <span style="color:${t.accent}; font-weight:800;">${String(idx + 1).padStart(2, '0')}.</span> ${mod.title || mod.module}
                </h4>
                ${mod.description ? `<p style="font-size:13px; margin-bottom:16px; color:${t.secondary};">${mod.description}</p>` : ''}
                <ul style="margin:0; padding-left:15px; list-style:none;">
                    ${(mod.features || mod.items || []).map(f => {
        let featureName = "";
        let descriptionLines = [f];

        if (typeof f === 'string') {
            if (f.includes(':')) {
                const parts = f.split(':');
                featureName = parts.shift().trim();
                const rest = parts.join(':').trim();
                descriptionLines = rest.split('\\\\n').map(line => line.trim()).filter(Boolean);
            } else {
                descriptionLines = f.split('\\\\n').map(line => line.trim()).filter(Boolean);
            }
        }

        return '<li style="margin-bottom:12px; page-break-inside:avoid;">' +
            '<div style="display:flex; align-items:flex-start; gap:8px;">' +
            '<div style="color:' + t.primary + '; font-weight:bold; margin-top:2px;">•</div>' +
            '<div>' +
            (featureName ? '<div style="font-weight:700; color:' + t.primary + '; font-size:13px; margin-bottom:2px;">' + featureName + '</div>' : '') +
            descriptionLines.map(line => '<div style="font-size:12px; color:' + t.secondary + '; line-height:1.5;">' + line + '</div>').join('') +
            '</div>' +
            '</div>' +
            '</li>';
    }).join('')}
                </ul>
            </div>
        `).join('')}
    </div>

    <!-- 4. Tech Stack & Team -->
    <div class="page-break">
        ${headerBlock('4. Technology & Resourcing')}
        
        <h3 style="font-size:18px; margin-bottom:15px;">Technology Stack</h3>
        <table style="margin-bottom: 40px;">
            <tr>
                <th style="width:30%;">Domain</th>
                <th>Proposed Technologies</th>
            </tr>
            ${Array.isArray(quotationData.techStack)
            ? `<tr><td>Core Tech</td><td>${(quotationData.techStack || []).map(t => `<span class="badge">${t}</span>`).join('')}</td></tr>`
            : Object.entries(quotationData.techStack || {}).map(([key, tools]) => `
                <tr>
                    <td style="text-transform:capitalize; font-weight:600; color:${t.secondary};">${key}</td>
                    <td>${(tools || []).map(tool => `<span class="badge">${tool}</span>`).join('')}</td>
                </tr>
            `).join('')}
        </table>

        <h3 style="font-size:18px; margin-bottom:15px; margin-top: 40px;">Proposed Team Structure</h3>
        <table>
            <tr>
                <th style="width:10%;">S.No.</th>
                <th style="width:60%;">Role</th>
                <th style="width:30%;">Allocation (Count)</th>
            </tr>
            ${(quotationData.proposedTeam || []).map((teamMember, idx) => `
                <tr>
                    <td>${idx + 1}</td>
                    <td style="font-weight:500;">${teamMember.role}</td>
                    <td>${teamMember.count} Resource(s)</td>
                </tr>
            `).join('')}
        </table>
    </div>

    <!-- 5. DETAILED COST BREAKDOWN (Key differentiator of Template 4) -->
    <div class="page-break">
        ${headerBlock('5. Detailed Cost Breakdown')}
        
        <p style="font-size:13px; color:${t.secondary}; margin-bottom:25px;">
            The following table provides a comprehensive, itemized breakdown of all engineering and project costs.
        </p>

        <table class="cost-breakdown-table">
            <tr>
                <th style="width:6%;">S.No.</th>
                <th style="width:20%;">Category</th>
                <th style="width:30%;">Scope & Description</th>
                <th style="width:12%; text-align:right;">Hours</th>
                <th style="width:14%; text-align:right;">Rate/Hr</th>
                <th style="width:18%; text-align:right;">Cost</th>
            </tr>
            ${costBreakdownRows}
            ${gstRow}
        </table>
    </div>

    <!-- 6. Payment & Timeline -->
    <div class="page-break" style="background:${t.bg}; padding: 25px; border-radius: 8px;">
        ${headerBlock('6. Payment & Timeline')}

        <h3 style="font-size:16px; margin-bottom:15px;">Payment Milestones</h3>
        <table>
            <tr>
                <th style="width:10%;">S.No.</th>
                <th style="width:40%;">Milestone</th>
                <th style="width:20%;">Percentage</th>
                <th style="width:30%;">Amount</th>
            </tr>
            ${(quotationData.costEstimation?.paymentPlan || quotationData.paymentPlan || []).map((p, idx) => `
                <tr>
                    <td>${idx + 1}</td>
                    <td>${typeof p === 'object' ? p.milestone : p}</td>
                    <td style="font-weight:600;">${typeof p === 'object' ? p.percentage : '-'}</td>
                    <td>${typeof p === 'object' ? p.amount : '-'}</td>
                </tr>
            `).join('')}
        </table>

        <h3 style="font-size:16px; margin-top:40px; margin-bottom:15px;">Implementation Timeline</h3>
        <table>
            <tr>
                <th style="width:10%;">S.No.</th>
                <th style="width:30%;">Phase</th>
                <th style="width:20%;">Duration</th>
                <th style="width:40%;">Key Deliverables</th>
            </tr>
            ${(quotationData.timeline || []).map((tl, idx) => `
                <tr>
                    <td>${idx + 1}</td>
                    <td style="font-weight:600;">${tl.phase}</td>
                    <td>${tl.duration}</td>
                    <td style="font-size:12px;">${tl.deliverables || (tl.tasks || []).join(', ')}</td>
                </tr>
            `).join('')}
        </table>
    </div>

    <!-- 7. Post-Deployment & Governance -->
    <div class="page-break">
        ${headerBlock('7. Post-Deployment & Governance')}

        <div style="margin-bottom: 30px;">
            <h4 style="font-size:15px; margin-bottom:5px; color:${t.primary};">Service Level Agreement (SLA)</h4>
            <div style="font-size:13px; margin-bottom:15px;"><strong>Coverage:</strong> ${quotationData.sla?.maintenanceCoverage || 'Standard Support'}</div>
            <table>
                <tr>
                    <th style="width:10%;">S.No.</th>
                    <th>Metric</th>
                    <th>Target</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Response Times</td>
                    <td><ul style="margin:0; padding-left:15px;">${(quotationData.sla?.responseTimes || []).map(r => `<li>${r}</li>`).join('')}</ul></td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Resolution Times</td>
                    <td><ul style="margin:0; padding-left:15px;">${(quotationData.sla?.resolutionTimes || []).map(r => `<li>${r}</li>`).join('')}</ul></td>
                </tr>
            </table>
        </div>

        <div class="highlight-box" style="padding:15px; margin-bottom:20px; border-left-color:${t.secondary}; background:${t.bg}; border-radius:4px;">
            <h4 style="font-size:14px; margin-bottom:5px;">Annual Maintenance Contract (AMC)</h4>
            <p style="font-size:13px; margin:0;">${quotationData.amc || 'Details to be appended.'}</p>
        </div>

        <div style="margin-bottom: 25px;">
            <h4 style="font-size:14px; margin-bottom:5px;">Change Request Management</h4>
            <p style="font-size:13px; color:${t.secondary}; margin:0;">${quotationData.changeRequest || 'Any additional features not outlined in the scope will be considered a Change Request (CR) and billed separately.'}</p>
        </div>

        <div style="margin-bottom: 25px;">
            <h4 style="font-size:14px; margin-bottom:5px;">Acceptance Criteria</h4>
            <ul style="margin:0; color:${t.secondary};">
                ${(quotationData.acceptanceCriteria || []).map(c => `<li>${c}</li>`).join('')}
            </ul>
        </div>

        <div style="margin-bottom: 25px;">
            <h4 style="font-size:14px; margin-bottom:5px;">Warranty</h4>
            <p style="font-size:13px; color:${t.secondary}; margin:0;">${quotationData.warranty || '60 Days defect liability period post UAT sign-off.'}</p>
        </div>
    </div>

    <!-- 8. Sign Off -->
    <div class="page-break">
        ${headerBlock('8. Sign Off & Acceptance')}

        <h3 style="font-size:18px; margin-bottom:15px;">Legal & Compliance</h3>
        <p style="font-size:13px; color:${t.secondary}; line-height: 1.8; margin-bottom:50px;">
            ${quotationData.legal || 'This document is strictly confidential and intended solely for the use of the individual or entity to whom it is addressed.'}
        </p>

        <div style="background:${t.bg}; padding:35px; border-top: 3px solid ${t.primary}; border-radius:8px;">
            <h3 style="font-size:16px; margin-bottom:45px; text-transform:uppercase;">Authorization & Acceptance</h3>
            
            <div style="display:grid; grid-template-columns: 1fr 1fr; gap:60px;">
                <div>
                    <div style="border-bottom:1px solid ${t.secondary}; height:40px; margin-bottom:12px;"></div>
                    <div style="font-size:13px; font-weight:700; color:${t.primary};">Authorized Signatory</div>
                    <div style="font-size:11px; color:${t.secondary};">ArgosMob Tech &amp; AI Pvt. Ltd.</div>
                    <div style="font-size:11px; color:${t.secondary}; margin-top:5px;">Date: ________________</div>
                </div>
                <div>
                    <div style="border-bottom:1px solid ${t.secondary}; height:40px; margin-bottom:12px;"></div>
                    <div style="font-size:13px; font-weight:700; color:${t.primary};">Authorized Signatory</div>
                    <div style="font-size:11px; color:${t.secondary};">${quotationData.clientName || 'Client'}</div>
                    <div style="font-size:11px; color:${t.secondary}; margin-top:5px;">Date: ________________</div>
                </div>
            </div>
        </div>
    </div>

  </td></tr></tbody>
</table>

</body>
</html>`;

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
        format: 'A4',
        preferCSSPageSize: true,
        printBackground: true,
        displayHeaderFooter: false,
    });

    await browser.close();
    return pdfBuffer;
};
