import {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, ShadingType, Table, TableRow,
    TableCell, WidthType, PageBreak, Header, Footer
} from 'docx';

/**
 * Generates a professionally styled Word document (.docx) from quotation data.
 * @param {Object} quotationData - The JSON generated by AI.
 * @param {string} style - 'corporate' | 'modern' | 'minimal'
 * @returns {Promise<Buffer>} The Docx buffer.
 */
export const generateQuotationWord = async (quotationData, style = 'corporate') => {

    // ── Theme colours ─────────────────────────────────────────────
    const themes = {
        corporate: { primary: '1A1A2E', secondary: '92400E', accent: 'FEF3C7', text: '1A1A2E', muted: '6B7280' },
        modern: { primary: '1A1A2E', secondary: 'D97706', accent: 'FEF3C7', text: '1A1A2E', muted: '6B7280' },
        minimal: { primary: '111111', secondary: '525252', accent: 'F5F5F5', text: '111111', muted: '737373' },
    };
    const t = themes[style] || themes.corporate;

    // ── Helpers ───────────────────────────────────────────────────

    /** Horizontal rule via a top-bordered paragraph */
    const hr = () => new Paragraph({
        border: { top: { color: t.primary, style: BorderStyle.SINGLE, size: 12 } },
        spacing: { before: 200, after: 200 },
        children: [],
    });

    /** Section number badge + title on same line */
    const sectionHeading = (num, title) => new Paragraph({
        spacing: { before: 400, after: 120 },
        children: [
            new TextRun({
                text: `  ${num}  `,
                bold: true,
                color: 'FFFFFF',
                highlight: 'darkBlue',   // nearest docx colour token
                size: 28,
            }),
            new TextRun({ text: '  ', size: 28 }),
            new TextRun({
                text: title.toUpperCase(),
                bold: true,
                color: t.primary,
                size: 32,
                font: 'Calibri',
            }),
        ],
    });

    /** H2-style sub-heading */
    const subHeading = (text) => new Paragraph({
        spacing: { before: 280, after: 80 },
        children: [
            new TextRun({
                text: text.toUpperCase(),
                bold: true,
                color: t.secondary,
                size: 22,
                font: 'Calibri',
                allCaps: true,
            }),
        ],
    });

    /** Renders an array as individual bullet paragraphs, or a plain string as a body paragraph */
    const renderArray = (data) => {
        if (Array.isArray(data)) {
            return data.map(pt => bullet(pt || ''));
        }
        return [new Paragraph({
            spacing: { after: 160 },
            children: [new TextRun({ text: data || '', size: 22, color: t.text, font: 'Calibri' })],
        })];
    };

    /** Bullet item with a styled dash */
    const bullet = (text) => new Paragraph({
        spacing: { before: 60, after: 60 },
        indent: { left: 400, hanging: 200 },
        children: [
            new TextRun({ text: '›  ', color: t.primary, bold: true, size: 22 }),
            new TextRun({ text, size: 22, color: t.text, font: 'Calibri' }),
        ],
    });

    /** Shaded info box (one paragraph with background) */
    const infoBox = (text, label) => new Paragraph({
        shading: { type: ShadingType.SOLID, color: t.accent, fill: t.accent },
        border: {
            left: { color: t.primary, style: BorderStyle.THICK, size: 12 },
            top: { color: t.accent, style: BorderStyle.SINGLE, size: 1 },
            bottom: { color: t.accent, style: BorderStyle.SINGLE, size: 1 },
            right: { color: t.accent, style: BorderStyle.SINGLE, size: 1 },
        },
        spacing: { before: 120, after: 120 },
        children: [
            ...(label ? [new TextRun({ text: `${label}  `, bold: true, color: t.primary, size: 22, font: 'Calibri' })] : []),
            new TextRun({ text, size: 22, color: t.text, font: 'Calibri' }),
        ],
    });

    /** Feature module card (heading + bullets, with left-border shading) */
    const moduleCard = (f) => [
        new Paragraph({
            shading: { type: ShadingType.SOLID, color: t.accent, fill: t.accent },
            border: { left: { color: t.primary, style: BorderStyle.THICK, size: 12 } },
            spacing: { before: 200, after: 60 },
            children: [
                new TextRun({
                    text: `  ${f.module}`,
                    bold: true,
                    color: t.primary,
                    size: 24,
                    font: 'Calibri',
                }),
            ],
        }),
        ...(f.items || []).map(item => bullet(`  ${item}`)),
        new Paragraph({ spacing: { after: 120 }, children: [] }),
    ];

    /** Investment highlight box */
    const priceBox = (estimate) => new Paragraph({
        alignment: AlignmentType.CENTER,
        shading: { type: ShadingType.SOLID, color: t.primary, fill: t.primary },
        spacing: { before: 240, after: 240 },
        children: [
            new TextRun({
                text: estimate || '',
                bold: true,
                color: 'FFFFFF',
                size: 40,
                font: 'Calibri',
            }),
        ],
    });

    /** Page break */
    const pageBreak = () => new Paragraph({ children: [new PageBreak()] });

    // ── Document ─────────────────────────────────────────────────

    const doc = new Document({
        creator: 'Argomsob Tech & AI',
        title: `${quotationData.industry} ${quotationData.projectType} — Proposal`,
        description: 'Strategic Proposal generated by Argomsob Tech & AI',
        styles: {
            default: {
                document: {
                    run: { font: 'Calibri', size: 22, color: t.text },
                },
            },
        },
        sections: [
            {
                properties: {
                    page: {
                        margin: { top: 1200, right: 1000, bottom: 1200, left: 1000 },
                    },
                },
                headers: {
                    default: new Header({
                        children: [
                            new Paragraph({
                                border: { bottom: { color: t.primary, style: BorderStyle.SINGLE, size: 8 } },
                                spacing: { after: 100 },
                                children: [
                                    new TextRun({ text: 'ARGOMSOB TECH & AI  |  ', bold: true, color: t.primary, size: 18, font: 'Calibri' }),
                                    new TextRun({ text: `Strategic Proposal — ${quotationData.industry} ${quotationData.projectType}`, color: t.muted, size: 18, font: 'Calibri' }),
                                ],
                            }),
                        ],
                    }),
                },
                footers: {
                    default: new Footer({
                        children: [
                            new Paragraph({
                                border: { top: { color: t.accent, style: BorderStyle.SINGLE, size: 6 } },
                                spacing: { before: 100 },
                                children: [
                                    new TextRun({ text: '123 Tech Park, Bangalore  |  +91 98765 43210  |  info@argomsob.tech', size: 16, color: t.muted, font: 'Calibri' }),
                                    new TextRun({ text: `   |   Confidential © ${new Date().getFullYear()} Argomsob Tech & AI`, size: 16, color: t.muted, font: 'Calibri' }),
                                ],
                            }),
                        ],
                    }),
                },
                children: [

                    // ══ COVER ═══════════════════════════════════════
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        spacing: { before: 1200, after: 200 },
                        children: [
                            new TextRun({
                                text: 'ARGOMSOB TECH & AI',
                                bold: true,
                                color: t.primary,
                                size: 52,
                                font: 'Calibri',
                                allCaps: true,
                            }),
                        ],
                    }),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 600 },
                        children: [
                            new TextRun({
                                text: 'Digital Engineering & AI Solutions',
                                color: t.muted,
                                size: 26,
                                font: 'Calibri',
                            }),
                        ],
                    }),
                    hr(),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        spacing: { before: 400, after: 200 },
                        children: [
                            new TextRun({
                                text: 'STRATEGIC PROPOSAL',
                                bold: true,
                                color: t.secondary,
                                size: 28,
                                font: 'Calibri',
                                allCaps: true,
                            }),
                        ],
                    }),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 800 },
                        children: [
                            new TextRun({
                                text: `${quotationData.industry || ''} — ${quotationData.projectType || ''}`,
                                bold: true,
                                color: t.primary,
                                size: 56,
                                font: 'Calibri',
                            }),
                        ],
                    }),
                    hr(),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        spacing: { before: 400 },
                        children: [
                            new TextRun({
                                text: `Prepared by Argomsob Tech & AI\n${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`,
                                color: t.muted,
                                size: 22,
                                font: 'Calibri',
                            }),
                        ],
                    }),

                    pageBreak(),

                    // ══ TABLE OF CONTENTS ════════════════════════════
                    new Paragraph({
                        spacing: { before: 200, after: 300 },
                        children: [
                            new TextRun({ text: 'TABLE OF CONTENTS', bold: true, color: t.primary, size: 36, font: 'Calibri', allCaps: true }),
                        ],
                    }),
                    hr(),
                    ...[
                        ['01', 'Executive Summary & Business Overview'],
                        ['02', 'Technical Vision & Architecture Strategy'],
                        ['03', 'Solution Architecture & Feature Breakdown'],
                        ['04', 'Security, Engineering Stack & Compliance'],
                        ['05', 'Project Methodology, Timeline & Investment'],
                    ].map(([num, title]) => new Paragraph({
                        spacing: { before: 120, after: 120 },
                        children: [
                            new TextRun({ text: `${num}.  `, bold: true, color: t.primary, size: 24, font: 'Calibri' }),
                            new TextRun({ text: title, size: 24, color: t.text, font: 'Calibri' }),
                        ],
                    })),

                    pageBreak(),

                    // ══ 01 EXECUTIVE SUMMARY ══════════════════════════
                    sectionHeading('01', 'Executive Summary'),
                    hr(),
                    subHeading('Business Context & Opportunity'),
                    ...renderArray(quotationData.overview),

                    pageBreak(),

                    // ══ 02 TECHNICAL VISION ═══════════════════════════
                    sectionHeading('02', 'Technical Vision'),
                    hr(),
                    subHeading('Architectural Strategy & Approach'),
                    ...renderArray(quotationData.scope),

                    pageBreak(),

                    // ══ 03 SOLUTION ARCHITECTURE ══════════════════════
                    sectionHeading('03', 'Solution Architecture'),
                    hr(),
                    subHeading('Core Modules & Feature Breakdown'),
                    ...(quotationData.features || []).flatMap(f => moduleCard(f)),

                    pageBreak(),

                    // ══ 04 SECURITY & STACK ═══════════════════════════
                    sectionHeading('04', 'Security & Engineering Stack'),
                    hr(),
                    subHeading('Security, Compliance & Data Privacy'),
                    ...renderArray(quotationData.security || ['OAuth 2.0 authentication and authorisation', 'AES-256 encryption for data at rest', 'TLS 1.3 for all data in transit', 'Regular vulnerability scans and penetration testing']),
                    subHeading('Technology Stack'),
                    ...(quotationData.techStack || []).map(tech => bullet(tech)),

                    pageBreak(),

                    // ══ 05 METHODOLOGY ════════════════════════════════
                    sectionHeading('05', 'Project Methodology & Investment'),
                    hr(),
                    subHeading('Development Methodology'),
                    ...renderArray(quotationData.methodology || ['Agile Scrum with 2-week sprints', 'CI/CD pipeline with automated testing', 'Bi-weekly stakeholder demos', 'Iterative delivery with UAT sign-off']),
                    subHeading('Delivery Roadmap'),
                    ...(quotationData.timeline || []).flatMap((t_item, i) => {
                        const phase = typeof t_item === 'object'
                            ? [t_item.phase || t_item.task || `Phase ${i + 1}`, t_item.duration ? `(${t_item.duration})` : ''].filter(Boolean).join(' ')
                            : t_item;
                        const tasks = typeof t_item === 'object' && Array.isArray(t_item.tasks) ? t_item.tasks : [];
                        return [
                            new Paragraph({
                                spacing: { before: 120, after: 60 },
                                indent: { left: 400, hanging: 200 },
                                children: [
                                    new TextRun({ text: `›  `, color: t.primary, bold: true, size: 22 }),
                                    new TextRun({ text: phase, bold: true, size: 22, color: t.primary, font: 'Calibri' }),
                                ],
                            }),
                            ...tasks.map(task => new Paragraph({
                                spacing: { before: 40, after: 40 },
                                indent: { left: 720 },
                                children: [
                                    new TextRun({ text: `–  ${task}`, size: 20, color: t.text, font: 'Calibri' }),
                                ],
                            })),
                        ];
                    }),

                    new Paragraph({ spacing: { after: 300 }, children: [] }),
                    subHeading('Total Project Investment'),
                    priceBox(quotationData.commercialEstimate),

                    new Paragraph({ spacing: { after: 200 }, children: [] }),
                    subHeading('Payment Schedule & Milestones'),
                    ...(quotationData.paymentPlan || []).map((plan, i) =>
                        infoBox(plan, `Milestone ${i + 1}`)
                    ),

                    new Paragraph({ spacing: { before: 400, after: 200 }, children: [] }),
                    new Paragraph({
                        shading: { type: ShadingType.SOLID, color: 'FEF3C7', fill: 'FEF3C7' },
                        border: { left: { color: '92400E', style: BorderStyle.THICK, size: 12 } },
                        spacing: { before: 60, after: 0 },
                        children: [new TextRun({ text: '⚠  IMPORTANT NOTES', bold: true, color: '92400E', size: 20, font: 'Calibri' })],
                    }),
                    new Paragraph({
                        shading: { type: ShadingType.SOLID, color: 'FEF3C7', fill: 'FEF3C7' },
                        border: { left: { color: '92400E', style: BorderStyle.THICK, size: 12 } },
                        spacing: { before: 40, after: 40 },
                        children: [new TextRun({ text: '•  GST @ 18% applicable separately on all invoices as per GoI norms.', size: 19, color: t.text, font: 'Calibri' })],
                    }),
                    new Paragraph({
                        shading: { type: ShadingType.SOLID, color: 'FEF3C7', fill: 'FEF3C7' },
                        border: { left: { color: '92400E', style: BorderStyle.THICK, size: 12 } },
                        spacing: { before: 20, after: 40 },
                        children: [new TextRun({ text: '•  3rd party API costs (SMS / WhatsApp / Maps / Payments) billed at actuals.', size: 19, color: t.text, font: 'Calibri' })],
                    }),
                    new Paragraph({
                        shading: { type: ShadingType.SOLID, color: 'FEF3C7', fill: 'FEF3C7' },
                        border: { left: { color: '92400E', style: BorderStyle.THICK, size: 12 } },
                        spacing: { before: 20, after: 60 },
                        children: [new TextRun({ text: '•  VPS hosting, domain, SSL, and infrastructure costs are billed separately.', size: 19, color: t.text, font: 'Calibri' })],
                    }),

                    new Paragraph({ spacing: { before: 400, after: 200 }, children: [] }),
                    hr(),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun({
                                text: 'This proposal is valid for 15 days from the date of issue.',
                                italics: true,
                                color: t.muted,
                                size: 20,
                                font: 'Calibri',
                            }),
                        ],
                    }),
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun({
                                text: 'Confidential — Argomsob Tech & AI  |  info@argomsob.tech',
                                color: t.muted,
                                size: 18,
                                font: 'Calibri',
                            }),
                        ],
                    }),
                ],
            },
        ],
    });

    return await Packer.toBuffer(doc);
};
